// overlay.jsx
// ─────────────────────────────────────────────────────────────────────
// Overlay store: keeps user edits separate from data.jsx.
//
// data.jsx is treated as the immutable seed (typically generated by an LLM
// from project documentation). The architect can add, edit and delete ADRs
// and containers from the UI; those mutations are stored as a diff in
// localStorage and merged on read into an "effective" blueprint.
//
// Shape of the stored overlay:
//
//   {
//     adrs:       { byId: { "adr.001": {<full or partial fields>} },
//                   created: ["adr.099", ...],
//                   deleted: ["adr.002"] },
//     containers: { byId, created, deleted, ... },
//   }
//
// Edits to seeded items merge field-by-field. Created items are stored whole.
// Deleted ids are filtered out on read.
//
// We intentionally avoid an event bus — components subscribe via the
// useOverlay hook and re-render when the overlay version bumps.

(function (global) {
  const KEY_PREFIX = "blueprint.overlay.";

  function key(blueprintName) {
    return KEY_PREFIX + (blueprintName || "default");
  }

  const EMPTY = {
    adrs:       { byId: {}, created: [], deleted: [] },
    containers: { byId: {}, created: [], deleted: [] },
    flows:      { byId: {}, created: [], deleted: [] },
    // Edges have no stable id. We key them by a composite string and store
    // separate buckets per kind. Each bucket has:
    //   patched: { "from__to": { ...patchFields } }   — overlay onto seed
    //   created: [ {from,to,...} ]                    — added by user
    //   deleted: [ "from__to" ]                       — removed from seed
    contextEdges:   { patched: {}, created: [], deleted: [] },
    containerEdges: { patched: {}, created: [], deleted: [] },
    // componentEdges live per-container, so the patched/deleted keys
    // include the container id: "containerId::from__to"; created entries
    // carry an extra `_container` field so we know where to put them.
    componentEdges: { patched: {}, created: [], deleted: [] },
  };

  function loadOverlay(blueprintName) {
    try {
      const raw = localStorage.getItem(key(blueprintName));
      if (!raw) return JSON.parse(JSON.stringify(EMPTY));
      const parsed = JSON.parse(raw);
      // Defensive: ensure all sections exist.
      return {
        adrs:       { ...EMPTY.adrs,       ...(parsed.adrs       || {}) },
        containers: { ...EMPTY.containers, ...(parsed.containers || {}) },
        flows:      { ...EMPTY.flows,      ...(parsed.flows      || {}) },
        contextEdges:   { ...EMPTY.contextEdges,   ...(parsed.contextEdges   || {}) },
        containerEdges: { ...EMPTY.containerEdges, ...(parsed.containerEdges || {}) },
        componentEdges: { ...EMPTY.componentEdges, ...(parsed.componentEdges || {}) },
      };
    } catch (_) {
      return JSON.parse(JSON.stringify(EMPTY));
    }
  }

  function saveOverlay(blueprintName, ov) {
    try {
      localStorage.setItem(key(blueprintName), JSON.stringify(ov));
    } catch (_) {}
  }

  // Apply the overlay to a base list of items keyed by `id`.
  // Returns: [ ...survivingSeedItemsMerged, ...createdItems ]
  function applyToList(seedList, section) {
    const deleted = new Set(section.deleted || []);
    const merged = (seedList || [])
      .filter((it) => !deleted.has(it.id))
      .map((it) => {
        const patch = section.byId && section.byId[it.id];
        return patch ? { ...it, ...patch } : it;
      });
    const createdIds = new Set(section.created || []);
    const created = [];
    Object.keys(section.byId || {}).forEach((id) => {
      if (createdIds.has(id) && !deleted.has(id)) {
        // For created items, the byId entry is the WHOLE object.
        created.push(section.byId[id]);
      }
    });
    return [...merged, ...created];
  }

  // Build the effective BP that the canvas should read.
  // We mutate a shallow copy so original data.jsx stays clean.
  function buildEffectiveBP(seed, overlay) {
    if (!seed) return seed;
    const eff = { ...seed };
    eff.adrs       = applyToList(seed.adrs       || [], overlay.adrs);
    eff.containers = applyToList(seed.containers || [], overlay.containers);
    eff.flows      = applyToList(seed.flows      || [], overlay.flows);
    eff.contextEdges   = applyToEdgeList(seed.contextEdges   || [], overlay.contextEdges);
    eff.containerEdges = applyToEdgeList(seed.containerEdges || [], overlay.containerEdges);
    eff.componentEdges = applyToComponentEdges(seed.componentEdges || {}, overlay.componentEdges);
    return eff;
  }

  // Edges live in flat arrays, keyed by `from__to` (no stable id).
  function edgeKey(e) { return `${e.from}__${e.to}`; }

  function applyToEdgeList(seedList, section) {
    const deleted = new Set(section.deleted || []);
    const merged = (seedList || [])
      .filter((e) => !deleted.has(edgeKey(e)))
      .map((e) => {
        const patch = section.patched && section.patched[edgeKey(e)];
        return patch ? { ...e, ...patch } : e;
      });
    const created = (section.created || []).filter((e) => !deleted.has(edgeKey(e)));
    return [...merged, ...created];
  }

  // componentEdges is { containerId: [...edges] }. Keys for patched/deleted
  // include the container id: "containerId::from__to". Created entries
  // carry `_container` to know where to slot them.
  function applyToComponentEdges(seedMap, section) {
    const deleted = new Set(section.deleted || []);
    const out = {};
    Object.keys(seedMap || {}).forEach((cid) => {
      out[cid] = (seedMap[cid] || [])
        .filter((e) => !deleted.has(`${cid}::${edgeKey(e)}`))
        .map((e) => {
          const patch = section.patched && section.patched[`${cid}::${edgeKey(e)}`];
          return patch ? { ...e, ...patch } : e;
        });
    });
    (section.created || []).forEach((e) => {
      const cid = e._container;
      if (!cid) return;
      if (deleted.has(`${cid}::${edgeKey(e)}`)) return;
      const { _container, ...clean } = e;
      if (!out[cid]) out[cid] = [];
      out[cid].push(clean);
    });
    return out;
  }

  // ── Public hook ──────────────────────────────────────────────────────
  // Components call `useOverlay()` and get { ov, setOv, ... mutators }.
  // Side-effect: also installs the effective BP on window.BLUEPRINT so the
  // canvas (which reads window.BLUEPRINT directly) sees merged data.

  function useOverlay() {
    const { useState, useEffect, useCallback, useMemo } = React;
    const seed = window.__BLUEPRINT_SEED || window.BLUEPRINT;
    // On first run, freeze the seed so subsequent overlay applications
    // always start from the original data.jsx, not a mutated copy.
    if (!window.__BLUEPRINT_SEED) {
      window.__BLUEPRINT_SEED = JSON.parse(JSON.stringify(window.BLUEPRINT));
    }

    const blueprintName = (seed && seed.meta && seed.meta.project) || "default";
    const [ov, setOvRaw] = useState(() => loadOverlay(blueprintName));
    const [version, setVersion] = useState(0);

    const persist = useCallback((next) => {
      setOvRaw(next);
      saveOverlay(blueprintName, next);
      // Update window.BLUEPRINT synchronously so any consumer that reads it
      // during the same render pass (e.g. the canvas useMemo when overlayVersion
      // bumps) sees fresh data. Without this, the version bump triggers a
      // recompute that still reads the previous BLUEPRINT.
      window.BLUEPRINT = buildEffectiveBP(window.__BLUEPRINT_SEED, next);
      window.dispatchEvent(new CustomEvent("blueprint:overlay-changed"));
      setVersion((v) => v + 1);
    }, [blueprintName]);

    // Also keep the legacy effect — it covers the very first render where
    // window.BLUEPRINT may not yet have been built from a stored overlay.
    useEffect(() => {
      window.BLUEPRINT = buildEffectiveBP(window.__BLUEPRINT_SEED, ov);
    }, []);

    // ── ADR mutators ─────────────────────────────────────────────────
    const upsertAdr = useCallback((adr) => {
      // adr must have id. If it's a seed id, we patch; if it's new, we mark
      // as created and store the whole object.
      const seedHasIt = (window.__BLUEPRINT_SEED.adrs || []).some((a) => a.id === adr.id);
      const next = JSON.parse(JSON.stringify(ov));
      if (seedHasIt) {
        next.adrs.byId[adr.id] = { ...(next.adrs.byId[adr.id] || {}), ...adr };
        next.adrs.deleted = next.adrs.deleted.filter((id) => id !== adr.id);
      } else {
        next.adrs.byId[adr.id] = { ...adr };
        if (!next.adrs.created.includes(adr.id)) next.adrs.created.push(adr.id);
        next.adrs.deleted = next.adrs.deleted.filter((id) => id !== adr.id);
      }
      persist(next);
    }, [ov, persist]);

    const deleteAdr = useCallback((id) => {
      const next = JSON.parse(JSON.stringify(ov));
      const isCreated = next.adrs.created.includes(id);
      if (isCreated) {
        // Created-only items: just drop them.
        next.adrs.created = next.adrs.created.filter((x) => x !== id);
        delete next.adrs.byId[id];
      } else {
        if (!next.adrs.deleted.includes(id)) next.adrs.deleted.push(id);
        // Keep any patch — irrelevant once deleted, but cheap.
      }
      persist(next);
    }, [ov, persist]);

    // ── Container mutators ───────────────────────────────────────────
    const upsertContainer = useCallback((c) => {
      const seedHasIt = (window.__BLUEPRINT_SEED.containers || []).some((x) => x.id === c.id);
      const next = JSON.parse(JSON.stringify(ov));
      if (seedHasIt) {
        next.containers.byId[c.id] = { ...(next.containers.byId[c.id] || {}), ...c };
        next.containers.deleted = next.containers.deleted.filter((id) => id !== c.id);
      } else {
        next.containers.byId[c.id] = { ...c };
        if (!next.containers.created.includes(c.id)) next.containers.created.push(c.id);
        next.containers.deleted = next.containers.deleted.filter((id) => id !== c.id);
      }
      persist(next);
    }, [ov, persist]);

    const deleteContainer = useCallback((id) => {
      const next = JSON.parse(JSON.stringify(ov));
      const isCreated = next.containers.created.includes(id);
      if (isCreated) {
        next.containers.created = next.containers.created.filter((x) => x !== id);
        delete next.containers.byId[id];
      } else {
        if (!next.containers.deleted.includes(id)) next.containers.deleted.push(id);
      }
      persist(next);
    }, [ov, persist]);

    // ── Flow mutators ────────────────────────────────────────────────
    const upsertFlow = useCallback((f) => {
      const seedHasIt = (window.__BLUEPRINT_SEED.flows || []).some((x) => x.id === f.id);
      const next = JSON.parse(JSON.stringify(ov));
      if (seedHasIt) {
        next.flows.byId[f.id] = { ...(next.flows.byId[f.id] || {}), ...f };
        next.flows.deleted = next.flows.deleted.filter((id) => id !== f.id);
      } else {
        next.flows.byId[f.id] = { ...f };
        if (!next.flows.created.includes(f.id)) next.flows.created.push(f.id);
        next.flows.deleted = next.flows.deleted.filter((id) => id !== f.id);
      }
      persist(next);
    }, [ov, persist]);

    const deleteFlow = useCallback((id) => {
      const next = JSON.parse(JSON.stringify(ov));
      const isCreated = next.flows.created.includes(id);
      if (isCreated) {
        next.flows.created = next.flows.created.filter((x) => x !== id);
        delete next.flows.byId[id];
      } else {
        if (!next.flows.deleted.includes(id)) next.flows.deleted.push(id);
      }
      persist(next);
    }, [ov, persist]);

    // ── Edge mutators ────────────────────────────────────────────────
    // `kind` is one of "contextEdges" | "containerEdges" | "componentEdges".
    // For componentEdges, `containerId` is required; otherwise it is ignored.
    const upsertEdge = useCallback((kind, edge, containerId) => {
      if (!edge || !edge.from || !edge.to) return;
      const next = JSON.parse(JSON.stringify(ov));
      const section = next[kind];
      if (!section) return;

      const seedList = kind === "componentEdges"
        ? ((window.__BLUEPRINT_SEED.componentEdges || {})[containerId] || [])
        : (window.__BLUEPRINT_SEED[kind] || []);
      const compositeKey = kind === "componentEdges"
        ? `${containerId}::${edge.from}__${edge.to}`
        : `${edge.from}__${edge.to}`;

      const seedHasIt = seedList.some((e) => e.from === edge.from && e.to === edge.to);

      // Drop any pending delete for this composite key.
      section.deleted = (section.deleted || []).filter((k) => k !== compositeKey);

      if (seedHasIt) {
        section.patched = section.patched || {};
        section.patched[compositeKey] = { ...(section.patched[compositeKey] || {}), ...edge };
      } else {
        // Created edge — replace any prior created with same key, then add.
        const matchKey = (e) => kind === "componentEdges"
          ? (e._container === containerId && e.from === edge.from && e.to === edge.to)
          : (e.from === edge.from && e.to === edge.to);
        section.created = (section.created || []).filter((e) => !matchKey(e));
        const stored = kind === "componentEdges"
          ? { ...edge, _container: containerId }
          : { ...edge };
        section.created.push(stored);
      }
      persist(next);
    }, [ov, persist]);

    // For edits where the user changed from/to: pass the original endpoints
    // (oldFrom/oldTo) so we can drop the old key and write the new one.
    const replaceEdge = useCallback((kind, oldEdge, newEdge, containerId) => {
      if (!oldEdge || !newEdge || !newEdge.from || !newEdge.to) return;
      const sameEndpoints = oldEdge.from === newEdge.from && oldEdge.to === newEdge.to;
      if (sameEndpoints) {
        upsertEdge(kind, newEdge, containerId);
        return;
      }
      // Endpoints changed — delete old, upsert new.
      const next = JSON.parse(JSON.stringify(ov));
      const section = next[kind];
      if (!section) return;
      const oldCompositeKey = kind === "componentEdges"
        ? `${containerId}::${oldEdge.from}__${oldEdge.to}`
        : `${oldEdge.from}__${oldEdge.to}`;
      const seedList = kind === "componentEdges"
        ? ((window.__BLUEPRINT_SEED.componentEdges || {})[containerId] || [])
        : (window.__BLUEPRINT_SEED[kind] || []);
      const oldIsSeed = seedList.some((e) => e.from === oldEdge.from && e.to === oldEdge.to);
      if (oldIsSeed) {
        if (!section.deleted.includes(oldCompositeKey)) section.deleted.push(oldCompositeKey);
        if (section.patched) delete section.patched[oldCompositeKey];
      } else {
        // Drop the created entry for the old edge.
        const matchOld = (e) => kind === "componentEdges"
          ? (e._container === containerId && e.from === oldEdge.from && e.to === oldEdge.to)
          : (e.from === oldEdge.from && e.to === oldEdge.to);
        section.created = (section.created || []).filter((e) => !matchOld(e));
      }

      // Now upsert the new edge into the same section.
      const newCompositeKey = kind === "componentEdges"
        ? `${containerId}::${newEdge.from}__${newEdge.to}`
        : `${newEdge.from}__${newEdge.to}`;
      const newSeedList = seedList; // same container for componentEdges
      const newIsSeed = newSeedList.some((e) => e.from === newEdge.from && e.to === newEdge.to);
      section.deleted = section.deleted.filter((k) => k !== newCompositeKey);
      if (newIsSeed) {
        section.patched = section.patched || {};
        section.patched[newCompositeKey] = { ...(section.patched[newCompositeKey] || {}), ...newEdge };
      } else {
        const matchNew = (e) => kind === "componentEdges"
          ? (e._container === containerId && e.from === newEdge.from && e.to === newEdge.to)
          : (e.from === newEdge.from && e.to === newEdge.to);
        section.created = (section.created || []).filter((e) => !matchNew(e));
        const stored = kind === "componentEdges"
          ? { ...newEdge, _container: containerId }
          : { ...newEdge };
        section.created.push(stored);
      }
      persist(next);
    }, [ov, persist, upsertEdge]);

    const deleteEdge = useCallback((kind, edge, containerId) => {
      if (!edge || !edge.from || !edge.to) return;
      const next = JSON.parse(JSON.stringify(ov));
      const section = next[kind];
      if (!section) return;

      const compositeKey = kind === "componentEdges"
        ? `${containerId}::${edge.from}__${edge.to}`
        : `${edge.from}__${edge.to}`;
      const seedList = kind === "componentEdges"
        ? ((window.__BLUEPRINT_SEED.componentEdges || {})[containerId] || [])
        : (window.__BLUEPRINT_SEED[kind] || []);
      const isSeed = seedList.some((e) => e.from === edge.from && e.to === edge.to);

      if (isSeed) {
        if (!section.deleted.includes(compositeKey)) section.deleted.push(compositeKey);
        if (section.patched) delete section.patched[compositeKey];
      } else {
        // Created-only — just remove from created list.
        const matchKey = (e) => kind === "componentEdges"
          ? (e._container === containerId && e.from === edge.from && e.to === edge.to)
          : (e.from === edge.from && e.to === edge.to);
        section.created = (section.created || []).filter((e) => !matchKey(e));
      }
      persist(next);
    }, [ov, persist]);

    // ── Bulk export / import ─────────────────────────────────────────
    const exportOverlay = useCallback(() => {
      return JSON.stringify(ov, null, 2);
    }, [ov]);

    const importOverlay = useCallback((json) => {
      try {
        const parsed = typeof json === "string" ? JSON.parse(json) : json;
        const next = {
          adrs:       { ...EMPTY.adrs,       ...(parsed.adrs       || {}) },
          containers: { ...EMPTY.containers, ...(parsed.containers || {}) },
          flows:      { ...EMPTY.flows,      ...(parsed.flows      || {}) },
          contextEdges:   { ...EMPTY.contextEdges,   ...(parsed.contextEdges   || {}) },
          containerEdges: { ...EMPTY.containerEdges, ...(parsed.containerEdges || {}) },
          componentEdges: { ...EMPTY.componentEdges, ...(parsed.componentEdges || {}) },
        };
        persist(next);
        return { ok: true };
      } catch (e) {
        return { ok: false, error: e.message };
      }
    }, [persist]);

    const resetOverlay = useCallback(() => {
      persist(JSON.parse(JSON.stringify(EMPTY)));
    }, [persist]);

    return {
      ov,
      version,
      upsertAdr, deleteAdr,
      upsertContainer, deleteContainer,
      upsertFlow, deleteFlow,
      upsertEdge, replaceEdge, deleteEdge,
      exportOverlay, importOverlay, resetOverlay,
    };
  }

  // ── Helpers exposed for ad-hoc id generation ───────────────────────
  function nextAdrId(currentList) {
    const nums = (currentList || [])
      .map((a) => parseInt((a.id.match(/(\d+)$/) || [])[1] || "0", 10))
      .filter((n) => !Number.isNaN(n));
    const max = nums.length ? Math.max(...nums) : 0;
    return `adr.${String(max + 1).padStart(3, "0")}`;
  }

  function nextContainerId(currentList, hint) {
    // hint: a slug like "myService". We try `c.${hint}` and fall back to
    // appending a number if it collides.
    const slug = (hint || "container")
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "")
      .slice(0, 24) || "container";
    const taken = new Set((currentList || []).map((c) => c.id));
    let candidate = `c.${slug}`;
    let n = 2;
    while (taken.has(candidate)) {
      candidate = `c.${slug}${n}`;
      n++;
    }
    return candidate;
  }

  function nextFlowId(currentList, hint) {
    const slug = (hint || "flow")
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "")
      .slice(0, 24) || "flow";
    const taken = new Set((currentList || []).map((f) => f.id));
    let candidate = `flow.${slug}`;
    let n = 2;
    while (taken.has(candidate)) {
      candidate = `flow.${slug}${n}`;
      n++;
    }
    return candidate;
  }

  global.useOverlay = useOverlay;
  global.overlayHelpers = { nextAdrId, nextContainerId, nextFlowId };
})(window);
